ci:
  skip: [flutter-format, flutter-analyze]
exclude: .devcontainer/devcontainer.json
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow
  - repo: https://github.com/Cretezy/flutter-format-pre-commit
    rev: 4a1df675bb74dea371c17934933e257e46f8dd98
    hooks:
      - id: flutter-format
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: 0bfdb7415bb2d02794a884bf2b763a92772001eb
    hooks:
      - id: flutter-analyze
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-case-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
